const GET_CATEGORIES = 'GET_CATEGORIES' as const;
const CREATE_TOKEN = 'CREATE_TOKEN' as const;
const SEARCH_NFTS = 'SEARCH_NFTS' as const;
const CREATE_COLLECTION = 'CREATE_COLLECTION' as const;

export default {
  GET_CATEGORIES,
  CREATE_TOKEN,
  SEARCH_NFTS,
  CREATE_COLLECTION,
};
