const SEARCH_COLLECTIONS = 'SEARCH_COLLECTIONS' as const;
const CREATE_COLLECTION = 'CREATE_COLLECTION' as const;
const GET_TRENDING_COLLECTIONS = 'GET_TRENDING_COLLECTIONS' as const;
const GET_TOP_COLLECTIONS = 'GET_TOP_COLLECTIONS' as const;

export default {
  SEARCH_COLLECTIONS,
  CREATE_COLLECTION,
  GET_TRENDING_COLLECTIONS,
  GET_TOP_COLLECTIONS,
};
