const GET_TOKEN_BALANCE = 'GET_TOKEN_BALANCE' as const;
const LOGIN = 'LOGIN' as const;
const UPDATE_USER_INFO = 'UPDATE_USER_INFO' as const;
const GET_SELF_COLLECTION = 'GET_SELF_COLLECTION' as const;
const EDIT_PROFILE_INFO = 'EDIT_PROFILE_INFO' as const;

export default {
  GET_TOKEN_BALANCE,
  LOGIN,
  UPDATE_USER_INFO,
  GET_SELF_COLLECTION,
  EDIT_PROFILE_INFO,
};
