export default {
  getMetamaskMessage: 'account/get_metamask_message/',
  metamaskLogin: 'account/metamask_login/',
  getProfileInfo: (id: string | number) => `/account/${id}/`,
  getSelfInfo: '/account/self/',
  getTrendingNfts: 'store/trending/',
  presearchNfts: 'store/presearch/',
  searchNfts: 'store/search/',
  getCategories: '/store/categories/',
  createNewToken: '/store/create_token/',
  getTokenById: (id: string | number) => `/store/token/${id}/`,
  set_on_auction: (id: string | number) => `/store/token/${id}/set_on_auction/`,
  buy: 'store/buy/',
  bid: 'store/bids/make_bid/',
};
